name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Prepare envirnoment
        uses: actions/setup-node@v4
        with:
            node-version: "22.x"
      - name: Install Bit
        run: SHELL=sh npx @teambit/bvm install
      - name: Install dependencies
        run: bit install
      - name: Verify Workspace
        run: bit ci verify