name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container:
      image: bitsrc/stable:1.9.124-alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: bit install
      - name: Verify Workspace
        run: bit ci verify
