name: Merge Pull Request

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  my-job:
    if: github.event.pull_request.merged == true   # skip “closed without merge”
    runs-on: ubuntu-latest
    container:
      image: bitsrc/stable:1.9.124-alpine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bit install
        env:
          BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_ACCESS_TOKEN }}
      
      - name: Merge lane
        run: bit ci merge -b
        env:
          BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_ACCESS_TOKEN }}
