name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  my-job:
    runs-on: ubuntu-latest
    container:
      image: bitsrc/stable:1.9.124
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bit install
        env:
          BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_ACCESS_TOKEN }}  
          
      - name: Run PR command
        run: bit ci pr -b
        env:
          BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_ACCESS_TOKEN }}
